# 版权 @2025 凹语言 作者。保留所有权利。

wa:
	go run ../../../main.go run number.wa < number.in

wz:
	go run ../../../main.go run number.wz < number.in

seat-wa:
	go run ../../../main.go run seat.wa < seat.in

seat-wz:
	go run ../../../main.go run seat.wz < seat.in

clean:

