# 版权 @2023 凹语言 作者。保留所有权利。

default:
	go run ../../../main.go array.wa
	go run ../../../main.go array_1.wa
	go run ../../../main.go closure.wa
	go run ../../../main.go global.wa
	go run ../../../main.go heart.wa
	go run ../../../main.go multi_ret.wa
	#go run ../../../main.go native_test.wa
	go run ../../../main.go prime.wa
	go run ../../../main.go ref.wa
	go run ../../../main.go slice.wa
	go run ../../../main.go string.wa
	go run ../../../main.go struct.wa

clean:

