# 版权 @2023 凹语言 作者。保留所有权利。

default:
	go run ../../../main.go run array.wa
	go run ../../../main.go run array_1.wa
	go run ../../../main.go run closure.wa
	go run ../../../main.go run global.wa
	go run ../../../main.go run heart.wa
	go run ../../../main.go run multi_ret.wa
	#go run ../../../main.go run native_test.wa
	go run ../../../main.go run prime.wa
	go run ../../../main.go run ref.wa
	go run ../../../main.go run slice.wa
	go run ../../../main.go run string.wa
	go run ../../../main.go run struct.wa

clean:

