// Auto Generated by https://wa-lang.org/wa/wat2c. DONOT EDIT!!!

// module wa-arduino-hello

#pragma once

#ifndef _app_H_
#define _app_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern uint8_t*      app_memory;
extern const int32_t app_memory_init_max_pages; // = 0;
extern const int32_t app_memory_init_pages; // = 0;
extern int32_t       app_memory_size; // = 0;

extern void app_init();

// func $loop
extern void app_loop();

#ifdef __cplusplus
} // extern C 
#endif

#endif // _app_H_
