# 版权 @2023 凹语言 作者。保留所有权利。

run:
	go run ../../../../main.go run -console .

build:
	go run ../../../../main.go build -wat2c-native .

fmt:
	go run ../../../../main.go fmt ./src/...

test:
	go run ../../../../main.go test .

clean:
	-rm a.out*
