// Copyright (C) 2026 武汉凹语言科技有限公司
// SPDX-License-Identifier: AGPL-3.0-or-later

package x64

import (
	"wa-lang.org/wa/internal/native/abi"
)

// 寄存器名字列表
var _Register = []string{
	// 通用寄存器
	REG_RAX: "rax",
	REG_RCX: "rcx",
	REG_RDX: "rdx",
	REG_RBX: "rbx",
	REG_RSP: "rsp",
	REG_RBP: "rbp",
	REG_RSI: "rsi",
	REG_RDI: "rdi",
	REG_R8:  "r8",
	REG_R9:  "r9",
	REG_R10: "r10",
	REG_R11: "r11",
	REG_R12: "r12",
	REG_R13: "r13",
	REG_R14: "r14",
	REG_R15: "r15",

	// 浮点数寄存器
	REG_XMM0: "xmm0",
	REG_XMM1: "xmm1",
	REG_XMM2: "xmm2",
	REG_XMM3: "xmm3",
	REG_XMM4: "xmm4",
	REG_XMM5: "xmm5",
	REG_XMM6: "xmm6",
	REG_XMM7: "xmm7",
}

// 寄存器名字列表
var _Register32 = []string{
	// 通用寄存器
	REG_RAX: "eax",
	REG_RCX: "ecx",
	REG_RDX: "edx",
	REG_RBX: "ebx",
	REG_RSP: "esp",
	REG_RBP: "ebp",
	REG_RSI: "esi",
	REG_RDI: "edi",
	REG_R8:  "r8d",
	REG_R9:  "r9d",
	REG_R10: "r10d",
	REG_R11: "r11d",
	REG_R12: "r12d",
	REG_R13: "r13d",
	REG_R14: "r14d",
	REG_R15: "r15d",

	// 浮点数寄存器
	REG_XMM0: "xmm0",
	REG_XMM1: "xmm1",
	REG_XMM2: "xmm2",
	REG_XMM3: "xmm3",
	REG_XMM4: "xmm4",
	REG_XMM5: "xmm5",
	REG_XMM6: "xmm6",
	REG_XMM7: "xmm7",
}

// 指令的名字
// 保持和指令定义相同的顺序
var _Anames = []string{
	AADD:       "add",
	AADDSD:     "addsd",
	AADDSS:     "addss",
	AAND:       "and",
	ACALL:      "call",
	ACDQ:       "cdq",
	ACMP:       "cmp",
	ACVTSI2SD:  "cvtsi2sd",
	ACVTTSD2SI: "cvttsd2si",
	ADIV:       "div",
	ADIVSD:     "divsd",
	ADIVSS:     "divss",
	AIDIV:      "idiv",
	AIMUL:      "imul",
	AJA:        "ja",
	AJE:        "je",
	AJMP:       "jmp",
	ALEA:       "lea",
	AMOV:       "mov",
	AMOVABS:    "movabs",
	AMOVQ:      "movq",
	AMOVSD:     "movsd",
	AMOVSS:     "movss",
	AMOVZX:     "movzx",
	AMULSD:     "mulsd",
	AMULSS:     "mulss",
	ANOP:       "nop",
	AOR:        "or",
	APOP:       "pop",
	APUSH:      "push",
	ARET:       "ret",
	ASAR:       "sar",
	ASETA:      "seta",
	ASETAE:     "setae",
	ASETB:      "setb",
	ASETBE:     "setbe",
	ASETE:      "sete",
	ASETG:      "setg",
	ASETGE:     "setge",
	ASETL:      "setl",
	ASETLE:     "setle",
	ASETNE:     "setne",
	ASETNP:     "setnp",
	ASHL:       "shl",
	ASUB:       "sub",
	ASUBSD:     "subsd",
	ASUBSS:     "subss",
	ASYSCALL:   "syscall",
	AUCOMISD:   "ucomisd",
	AXOR:       "xor",
}

// 假设 AMAX 是指令枚举的最大值
// 假设 AMAX 是指令枚举的最大值
var x64ModeTable = [...]abi.X64Mode{
	AADD:       abi.X64Mode_Binary,
	AADDSD:     abi.X64Mode_Binary,
	AADDSS:     abi.X64Mode_Binary,
	AAND:       abi.X64Mode_Binary,
	ACDQ:       abi.X64Mode_NoArgs,
	ACALL:      abi.X64Mode_Unary,
	ACMP:       abi.X64Mode_Binary,
	ACVTSI2SD:  abi.X64Mode_Binary,
	ACVTTSD2SI: abi.X64Mode_Binary,
	ADIV:       abi.X64Mode_Unary,
	ADIVSD:     abi.X64Mode_Binary,
	ADIVSS:     abi.X64Mode_Binary,
	AIDIV:      abi.X64Mode_Unary,
	AIMUL:      abi.X64Mode_Binary,
	AJA:        abi.X64Mode_Unary,
	AJE:        abi.X64Mode_Unary,
	AJMP:       abi.X64Mode_Unary,
	ALEA:       abi.X64Mode_Binary,
	AMOV:       abi.X64Mode_Binary,
	AMOVABS:    abi.X64Mode_Binary,
	AMOVQ:      abi.X64Mode_Binary,
	AMOVSD:     abi.X64Mode_Binary,
	AMOVSS:     abi.X64Mode_Binary,
	AMOVZX:     abi.X64Mode_Binary,
	AMULSD:     abi.X64Mode_Binary,
	AMULSS:     abi.X64Mode_Binary,
	ANOP:       abi.X64Mode_NoArgs,
	AOR:        abi.X64Mode_Binary,
	APOP:       abi.X64Mode_Unary,
	APUSH:      abi.X64Mode_Unary,
	ARET:       abi.X64Mode_NoArgs,
	ASAR:       abi.X64Mode_Binary,
	ASETA:      abi.X64Mode_Unary,
	ASETAE:     abi.X64Mode_Unary,
	ASETB:      abi.X64Mode_Unary,
	ASETBE:     abi.X64Mode_Unary,
	ASETE:      abi.X64Mode_Unary,
	ASETG:      abi.X64Mode_Unary,
	ASETGE:     abi.X64Mode_Unary,
	ASETL:      abi.X64Mode_Unary,
	ASETLE:     abi.X64Mode_Unary,
	ASETNE:     abi.X64Mode_Unary,
	ASETNP:     abi.X64Mode_Unary,
	ASHL:       abi.X64Mode_Binary,
	ASUB:       abi.X64Mode_Binary,
	ASUBSD:     abi.X64Mode_Binary,
	ASUBSS:     abi.X64Mode_Binary,
	ASYSCALL:   abi.X64Mode_NoArgs,
	AUCOMISD:   abi.X64Mode_Binary,
	AXOR:       abi.X64Mode_Binary,

	ALAST: 0,
}
