// Copyright (C) 2026 武汉凹语言科技有限公司
// SPDX-License-Identifier: AGPL-3.0-or-later

package x64

// 寄存器名字列表
var _Register = []string{
	// 指针计数器
	REG_RIP: "rip",

	// 低8位寄存器
	REG_AL:   "al",
	REG_BL:   "bl",
	REG_CL:   "cl",
	REG_DL:   "dl",
	REG_SIL:  "sil",
	REG_DIL:  "dil",
	REG_BPL:  "bpl",
	REG_SPL:  "spl",
	REG_R8B:  "r8b",
	REG_R9B:  "r9b",
	REG_R10B: "r10b",
	REG_R11B: "r11b",
	REG_R12B: "r12b",
	REG_R13B: "r13b",
	REG_R14B: "r14b",
	REG_R15B: "r15b",

	// 高8位寄存器
	REG_AH: "ah",
	REG_BH: "bh",
	REG_CH: "ch",
	REG_DH: "dh",

	// 16位寄存器
	REG_AX:   "ax",
	REG_BX:   "bx",
	REG_CX:   "cx",
	REG_DX:   "dx",
	REG_SI:   "si",
	REG_DI:   "di",
	REG_BP:   "bp",
	REG_SP:   "sp",
	REG_R8W:  "r8w",
	REG_R9W:  "r9w",
	REG_R10W: "r10w",
	REG_R11W: "r11w",
	REG_R12W: "r12w",
	REG_R13W: "r13w",
	REG_R14W: "r14w",
	REG_R15W: "r15w",

	// 32位寄存器
	REG_EAX:  "eax",
	REG_EBX:  "ebx",
	REG_ECX:  "ecx",
	REG_EDX:  "edx",
	REG_ESI:  "esi",
	REG_EDI:  "edi",
	REG_EBP:  "ebp",
	REG_ESP:  "esp",
	REG_R8D:  "r8d",
	REG_R9D:  "r9d",
	REG_R10D: "r10d",
	REG_R11D: "r11d",
	REG_R12D: "r12d",
	REG_R13D: "r13d",
	REG_R14D: "r14d",
	REG_R15D: "r15d",

	// 64位寄存器
	REG_RAX: "rax",
	REG_RCX: "rcx",
	REG_RDX: "rdx",
	REG_RBX: "rbx",
	REG_RSP: "rsp",
	REG_RBP: "rbp",
	REG_RSI: "rsi",
	REG_RDI: "rdi",
	REG_R8:  "r8",
	REG_R9:  "r9",
	REG_R10: "r10",
	REG_R11: "r11",
	REG_R12: "r12",
	REG_R13: "r13",
	REG_R14: "r14",
	REG_R15: "r15",

	// 浮点数寄存器
	REG_XMM0: "xmm0",
	REG_XMM1: "xmm1",
	REG_XMM2: "xmm2",
	REG_XMM3: "xmm3",
	REG_XMM4: "xmm4",
	REG_XMM5: "xmm5",
	REG_XMM6: "xmm6",
	REG_XMM7: "xmm7",
}

// 寄存器名字列表
var _Register32 = []string{
	// 通用寄存器
	REG_RAX: "eax",
	REG_RCX: "ecx",
	REG_RDX: "edx",
	REG_RBX: "ebx",
	REG_RSP: "esp",
	REG_RBP: "ebp",
	REG_RSI: "esi",
	REG_RDI: "edi",
	REG_R8:  "r8d",
	REG_R9:  "r9d",
	REG_R10: "r10d",
	REG_R11: "r11d",
	REG_R12: "r12d",
	REG_R13: "r13d",
	REG_R14: "r14d",
	REG_R15: "r15d",

	// 浮点数寄存器
	REG_XMM0: "xmm0",
	REG_XMM1: "xmm1",
	REG_XMM2: "xmm2",
	REG_XMM3: "xmm3",
	REG_XMM4: "xmm4",
	REG_XMM5: "xmm5",
	REG_XMM6: "xmm6",
	REG_XMM7: "xmm7",
}

// 指令的名字
// 保持和指令定义相同的顺序
var _Anames = []string{
	AADD:       "add",
	AADDSD:     "addsd",
	AADDSS:     "addss",
	AAND:       "and",
	ACALL:      "call",
	ACDQ:       "cdq",
	ACMP:       "cmp",
	ACVTSI2SD:  "cvtsi2sd",
	ACVTSS2SD:  "cvtss2sd",
	ACVTTSD2SI: "cvttsd2si",
	ADEC:       "dec",
	ADIV:       "div",
	ADIVSD:     "divsd",
	ADIVSS:     "divss",
	AIDIV:      "idiv",
	AIMUL:      "imul",
	AINC:       "inc",
	AJA:        "ja",
	AJB:        "jb",
	AJE:        "je",
	AJGE:       "jge",
	AJMP:       "jmp",
	AJNS:       "jns",
	AJNZ:       "jnz",
	AJZ:        "jz",
	ALEA:       "lea",
	AMOV:       "mov",
	AMOVABS:    "movabs",
	AMOVQ:      "movq",
	AMOVSD:     "movsd",
	AMOVSS:     "movss",
	AMOVSXD:    "movsxd",
	AMOVZX:     "movzx",
	AMULSD:     "mulsd",
	AMULSS:     "mulss",
	ANEG:       "neg",
	ANOP:       "nop",
	AOR:        "or",
	APOP:       "pop",
	APUSH:      "push",
	ARET:       "ret",
	ASAR:       "sar",
	ASETA:      "seta",
	ASETAE:     "setae",
	ASETB:      "setb",
	ASETBE:     "setbe",
	ASETE:      "sete",
	ASETG:      "setg",
	ASETGE:     "setge",
	ASETL:      "setl",
	ASETLE:     "setle",
	ASETNE:     "setne",
	ASETNP:     "setnp",
	ASHL:       "shl",
	ASTD:       "std",
	ASUB:       "sub",
	ASUBSD:     "subsd",
	ASUBSS:     "subss",
	ASYSCALL:   "syscall",
	ATEST:      "test",
	AUCOMISD:   "ucomisd",
	AXOR:       "xor",
}
