# 版权 @2025 凹语言 作者。保留所有权利。

default:
	go run ../../../main.go run edit.wz < edit1.in

wa:
	go run ../../../main.go run edit.wa < edit1.in
	go run ../../../main.go run edit.wa < edit4.in

wz:
	go run ../../../main.go run edit.wz < edit1.in
	go run ../../../main.go run edit.wz < edit4.in


clean:

