// Code generated by stringer -i a.out.go -o anames.go -p loong64; DO NOT EDIT.

package loong64

// 寄存器名字列表
var _Register = []string{
	// 通用寄存器
	REG_R0:  "R0",
	REG_R1:  "R1",
	REG_R2:  "R2",
	REG_R3:  "R3",
	REG_R4:  "R4",
	REG_R5:  "R5",
	REG_R6:  "R6",
	REG_R7:  "R7",
	REG_R8:  "R8",
	REG_R9:  "R9",
	REG_R10: "R10",
	REG_R11: "R11",
	REG_R12: "R12",
	REG_R13: "R13",
	REG_R14: "R14",
	REG_R15: "R15",
	REG_R16: "R16",
	REG_R17: "R17",
	REG_R18: "R18",
	REG_R19: "R19",
	REG_R20: "R20",
	REG_R21: "R21",
	REG_R22: "R22",
	REG_R23: "R23",
	REG_R24: "R24",
	REG_R25: "R25",
	REG_R26: "R26",
	REG_R27: "R27",
	REG_R28: "R28",
	REG_R29: "R29",
	REG_R30: "R30",
	REG_R31: "R31",

	// 浮点数寄存器(F/D扩展)
	REG_F0:  "F0",
	REG_F1:  "F1",
	REG_F2:  "F2",
	REG_F3:  "F3",
	REG_F4:  "F4",
	REG_F5:  "F5",
	REG_F6:  "F6",
	REG_F7:  "F7",
	REG_F8:  "F8",
	REG_F9:  "F9",
	REG_F10: "F10",
	REG_F11: "F11",
	REG_F12: "F12",
	REG_F13: "F13",
	REG_F14: "F14",
	REG_F15: "F15",
	REG_F16: "F16",
	REG_F17: "F17",
	REG_F18: "F18",
	REG_F19: "F19",
	REG_F20: "F20",
	REG_F21: "F21",
	REG_F22: "F22",
	REG_F23: "F23",
	REG_F24: "F24",
	REG_F25: "F25",
	REG_F26: "F26",
	REG_F27: "F27",
	REG_F28: "F28",
	REG_F29: "F29",
	REG_F30: "F30",
	REG_F31: "F31",
}

// 寄存器别名
var _RegisterAlias = []string{
	REG_ZERO: "ZERO", // 零寄存器
	REG_RA:   "RA",   // 返回地址
	REG_TP:   "TP",   // 线程指针
	REG_SP:   "SP",   // 栈指针
	REG_A0:   "A0",   // 函数参数/返回值
	REG_A1:   "A1",   // 函数参数/返回值
	REG_A2:   "A2",   // 函数参数
	REG_A3:   "A3",   // 函数参数
	REG_A4:   "A4",   // 函数参数
	REG_A5:   "A5",   // 函数参数
	REG_A6:   "A6",   // 函数参数
	REG_A7:   "A7",   // 函数参数
	REG_T0:   "T0",   // 临时变量
	REG_T1:   "T1",   // 临时变量
	REG_T2:   "T2",   // 临时变量
	REG_T3:   "T3",   // 临时变量
	REG_T4:   "T4",   // 临时变量
	REG_T5:   "T5",   // 临时变量
	REG_T6:   "T6",   // 临时变量
	REG_T7:   "T7",   // 临时变量
	REG_T8:   "T8",   // 临时变量
	REG_X:    "X",    // 保留寄存器
	REG_FP:   "FP",   // 帧指针
	REG_S0:   "S0",   // Saved register
	REG_S1:   "S1",   // Saved register
	REG_S2:   "S2",   // Saved register
	REG_S3:   "S3",   // Saved register
	REG_S4:   "S4",   // Saved register
	REG_S5:   "S5",   // Saved register
	REG_S6:   "S6",   // Saved register
	REG_S7:   "S7",   // Saved register
	REG_S8:   "S8",   // Saved register

	REG_FA0:  "FA0",  // 函数参数/返回值
	REG_FA1:  "FA1",  // 函数参数/返回值
	REG_FA2:  "FA2",  // 函数参数
	REG_FA3:  "FA3",  // 函数参数
	REG_FA4:  "FA4",  // 函数参数
	REG_FA5:  "FA5",  // 函数参数
	REG_FA6:  "FA6",  // 函数参数
	REG_FA7:  "FA7",  // 函数参数
	REG_FT0:  "FT0",  // 临时变量
	REG_FT1:  "FT1",  // 临时变量
	REG_FT2:  "FT2",  // 临时变量
	REG_FT3:  "FT3",  // 临时变量
	REG_FT4:  "FT4",  // 临时变量
	REG_FT5:  "FT5",  // 临时变量
	REG_FT6:  "FT6",  // 临时变量
	REG_FT7:  "FT7",  // 临时变量
	REG_FT8:  "FT8",  // 临时变量
	REG_FT9:  "FT9",  // 临时变量
	REG_FT10: "FT10", // 临时变量
	REG_FT11: "FT11", // 临时变量
	REG_FT12: "FT12", // 临时变量
	REG_FT13: "FT13", // 临时变量
	REG_FT14: "FT14", // 临时变量
	REG_FT15: "FT15", // 临时变量
	REG_FS0:  "FS0",  // Saved register
	REG_FS1:  "FS1",  // Saved register
	REG_FS2:  "FS2",  // Saved register
	REG_FS3:  "FS3",  // Saved register
	REG_FS4:  "FS4",  // Saved register
	REG_FS5:  "FS5",  // Saved register
	REG_FS6:  "FS6",  // Saved register
	REG_FS7:  "FS7",  // Saved register
}
