// Code generated by stringer -i a.out.go -o anames.go -p loong64; DO NOT EDIT.

package loong64

// 寄存器名字列表
var _Register = []string{
	// 通用寄存器
	REG_R0:  "R0",
	REG_R1:  "R1",
	REG_R2:  "R2",
	REG_R3:  "R3",
	REG_R4:  "R4",
	REG_R5:  "R5",
	REG_R6:  "R6",
	REG_R7:  "R7",
	REG_R8:  "R8",
	REG_R9:  "R9",
	REG_R10: "R10",
	REG_R11: "R11",
	REG_R12: "R12",
	REG_R13: "R13",
	REG_R14: "R14",
	REG_R15: "R15",
	REG_R16: "R16",
	REG_R17: "R17",
	REG_R18: "R18",
	REG_R19: "R19",
	REG_R20: "R20",
	REG_R21: "R21",
	REG_R22: "R22",
	REG_R23: "R23",
	REG_R24: "R24",
	REG_R25: "R25",
	REG_R26: "R26",
	REG_R27: "R27",
	REG_R28: "R28",
	REG_R29: "R29",
	REG_R30: "R30",
	REG_R31: "R31",

	// 浮点数寄存器(F/D扩展)
	REG_F0:  "F0",
	REG_F1:  "F1",
	REG_F2:  "F2",
	REG_F3:  "F3",
	REG_F4:  "F4",
	REG_F5:  "F5",
	REG_F6:  "F6",
	REG_F7:  "F7",
	REG_F8:  "F8",
	REG_F9:  "F9",
	REG_F10: "F10",
	REG_F11: "F11",
	REG_F12: "F12",
	REG_F13: "F13",
	REG_F14: "F14",
	REG_F15: "F15",
	REG_F16: "F16",
	REG_F17: "F17",
	REG_F18: "F18",
	REG_F19: "F19",
	REG_F20: "F20",
	REG_F21: "F21",
	REG_F22: "F22",
	REG_F23: "F23",
	REG_F24: "F24",
	REG_F25: "F25",
	REG_F26: "F26",
	REG_F27: "F27",
	REG_F28: "F28",
	REG_F29: "F29",
	REG_F30: "F30",
	REG_F31: "F31",
}

// 寄存器名字列表(中文)
var _ZhRegister = []string{
	// 通用寄存器
	REG_R0:  "甲格",
	REG_R1:  "乙格",
	REG_R2:  "丙格",
	REG_R3:  "丁格",
	REG_R4:  "戊格",
	REG_R5:  "己格",
	REG_R6:  "庚格",
	REG_R7:  "辛格",
	REG_R8:  "壬格",
	REG_R9:  "癸格",
	REG_R10: "子格",
	REG_R11: "丑格",
	REG_R12: "寅格",
	REG_R13: "卯格",
	REG_R14: "辰格",
	REG_R15: "巳格",
	REG_R16: "午格",
	REG_R17: "未格",
	REG_R18: "申格",
	REG_R19: "酉格",
	REG_R20: "戌格",
	REG_R21: "亥格",
	REG_R22: "乾格",
	REG_R23: "坤格",
	REG_R24: "震格",
	REG_R25: "巽格",
	REG_R26: "坎格",
	REG_R27: "离格",
	REG_R28: "艮格",
	REG_R29: "兑格",
	REG_R30: "阴格",
	REG_R31: "阳格",

	// 浮点数寄存器(F/D扩展)
	REG_F0:  "甲皿",
	REG_F1:  "乙皿",
	REG_F2:  "丙皿",
	REG_F3:  "丁皿",
	REG_F4:  "戊皿",
	REG_F5:  "己皿",
	REG_F6:  "庚皿",
	REG_F7:  "辛皿",
	REG_F8:  "壬皿",
	REG_F9:  "癸皿",
	REG_F10: "子皿",
	REG_F11: "丑皿",
	REG_F12: "寅皿",
	REG_F13: "卯皿",
	REG_F14: "辰皿",
	REG_F15: "巳皿",
	REG_F16: "午皿",
	REG_F17: "未皿",
	REG_F18: "申皿",
	REG_F19: "酉皿",
	REG_F20: "戌皿",
	REG_F21: "亥皿",
	REG_F22: "乾皿",
	REG_F23: "坤皿",
	REG_F24: "震皿",
	REG_F25: "巽皿",
	REG_F26: "坎皿",
	REG_F27: "离皿",
	REG_F28: "艮皿",
	REG_F29: "兑皿",
	REG_F30: "阴皿",
	REG_F31: "阳皿",
}

// 寄存器别名
var _RegisterAlias = []string{
	REG_ZERO: "ZERO", // 零寄存器
	REG_RA:   "RA",   // 返回地址
	REG_TP:   "TP",   // 线程指针
	REG_SP:   "SP",   // 栈指针
	REG_A0:   "A0",   // 函数参数/返回值
	REG_A1:   "A1",   // 函数参数/返回值
	REG_A2:   "A2",   // 函数参数
	REG_A3:   "A3",   // 函数参数
	REG_A4:   "A4",   // 函数参数
	REG_A5:   "A5",   // 函数参数
	REG_A6:   "A6",   // 函数参数
	REG_A7:   "A7",   // 函数参数
	REG_T0:   "T0",   // 临时变量
	REG_T1:   "T1",   // 临时变量
	REG_T2:   "T2",   // 临时变量
	REG_T3:   "T3",   // 临时变量
	REG_T4:   "T4",   // 临时变量
	REG_T5:   "T5",   // 临时变量
	REG_T6:   "T6",   // 临时变量
	REG_T7:   "T7",   // 临时变量
	REG_T8:   "T8",   // 临时变量
	REG_X:    "X",    // 保留寄存器
	REG_FP:   "FP",   // 帧指针
	REG_S0:   "S0",   // Saved register
	REG_S1:   "S1",   // Saved register
	REG_S2:   "S2",   // Saved register
	REG_S3:   "S3",   // Saved register
	REG_S4:   "S4",   // Saved register
	REG_S5:   "S5",   // Saved register
	REG_S6:   "S6",   // Saved register
	REG_S7:   "S7",   // Saved register
	REG_S8:   "S8",   // Saved register

	REG_FA0:  "FA0",  // 函数参数/返回值
	REG_FA1:  "FA1",  // 函数参数/返回值
	REG_FA2:  "FA2",  // 函数参数
	REG_FA3:  "FA3",  // 函数参数
	REG_FA4:  "FA4",  // 函数参数
	REG_FA5:  "FA5",  // 函数参数
	REG_FA6:  "FA6",  // 函数参数
	REG_FA7:  "FA7",  // 函数参数
	REG_FT0:  "FT0",  // 临时变量
	REG_FT1:  "FT1",  // 临时变量
	REG_FT2:  "FT2",  // 临时变量
	REG_FT3:  "FT3",  // 临时变量
	REG_FT4:  "FT4",  // 临时变量
	REG_FT5:  "FT5",  // 临时变量
	REG_FT6:  "FT6",  // 临时变量
	REG_FT7:  "FT7",  // 临时变量
	REG_FT8:  "FT8",  // 临时变量
	REG_FT9:  "FT9",  // 临时变量
	REG_FT10: "FT10", // 临时变量
	REG_FT11: "FT11", // 临时变量
	REG_FT12: "FT12", // 临时变量
	REG_FT13: "FT13", // 临时变量
	REG_FT14: "FT14", // 临时变量
	REG_FT15: "FT15", // 临时变量
	REG_FS0:  "FS0",  // Saved register
	REG_FS1:  "FS1",  // Saved register
	REG_FS2:  "FS2",  // Saved register
	REG_FS3:  "FS3",  // Saved register
	REG_FS4:  "FS4",  // Saved register
	REG_FS5:  "FS5",  // Saved register
	REG_FS6:  "FS6",  // Saved register
	REG_FS7:  "FS7",  // Saved register
}

var _ZhRegisterAlias = []string{
	REG_ZERO: "零格",  // 零寄存器
	REG_RA:   "回格",  // 返回地址
	REG_TP:   "线格",  // 线程指针
	REG_SP:   "栈格",  // 栈指针
	REG_FP:   "帧格",  // 帧指针
	REG_A0:   "参甲格", // 函数参数/返回值
	REG_A1:   "参乙格", // 函数参数/返回值
	REG_A2:   "参丙格", // 函数参数
	REG_A3:   "参丁格", // 函数参数
	REG_A4:   "参戊格", // 函数参数
	REG_A5:   "参己格", // 函数参数
	REG_A6:   "参庚格", // 函数参数
	REG_A7:   "参辛格", // 函数参数
	REG_T0:   "暂甲格", // 临时变量
	REG_T1:   "暂乙格", // 临时变量
	REG_T2:   "暂丙格", // 临时变量
	REG_T3:   "暂丁格", // 临时变量
	REG_T4:   "暂戊格", // 临时变量
	REG_T5:   "暂己格", // 临时变量
	REG_T6:   "暂庚格", // 临时变量
	REG_T7:   "暂辛格", // 临时变量
	REG_T8:   "暂壬格", // 临时变量
	REG_X:    "保留格", // 保留寄存器
	REG_S0:   "守甲格", // Saved register
	REG_S1:   "守乙格", // Saved register
	REG_S2:   "守丙格", // Saved register
	REG_S3:   "守丁格", // Saved register
	REG_S4:   "守戊格", // Saved register
	REG_S5:   "守己格", // Saved register
	REG_S6:   "守庚格", // Saved register
	REG_S7:   "守辛格", // Saved register
	REG_S8:   "守壬格", // Saved register

	REG_FA0:  "参甲皿", // 函数参数/返回值
	REG_FA1:  "参乙皿", // 函数参数/返回值
	REG_FA2:  "参丙皿", // 函数参数
	REG_FA3:  "参丁皿", // 函数参数
	REG_FA4:  "参戊皿", // 函数参数
	REG_FA5:  "参己皿", // 函数参数
	REG_FA6:  "参庚皿", // 函数参数
	REG_FA7:  "参辛皿", // 函数参数
	REG_FT0:  "暂甲皿", // 临时变量
	REG_FT1:  "暂乙皿", // 临时变量
	REG_FT2:  "暂丙皿", // 临时变量
	REG_FT3:  "暂丁皿", // 临时变量
	REG_FT4:  "暂戊皿", // 临时变量
	REG_FT5:  "暂己皿", // 临时变量
	REG_FT6:  "暂庚皿", // 临时变量
	REG_FT7:  "暂辛皿", // 临时变量
	REG_FT8:  "暂壬皿", // 临时变量
	REG_FT9:  "暂癸皿", // 临时变量
	REG_FT10: "暂子皿", // 临时变量
	REG_FT11: "暂丑皿", // 临时变量
	REG_FT12: "暂寅皿", // 临时变量
	REG_FT13: "暂卯皿", // 临时变量
	REG_FT14: "暂辰皿", // 临时变量
	REG_FT15: "暂巳皿", // 临时变量
	REG_FS0:  "守甲皿", // Saved register
	REG_FS1:  "守乙皿", // Saved register
	REG_FS2:  "守丙皿", // Saved register
	REG_FS3:  "守丁皿", // Saved register
	REG_FS4:  "守戊皿", // Saved register
	REG_FS5:  "守己皿", // Saved register
	REG_FS6:  "守庚皿", // Saved register
	REG_FS7:  "守辛皿", // Saved register
}

// TODO: 中文指令集
var _ZhAnames = []string{
	AADDI_D:       "某加常.长整",
	AADDI_W:       "某加常.普整",
	AADDU16I_D:    "某加常.长整.十六常",
	AADD_D:        "某加某.长整",
	AADD_W:        "某加某.普整",
	AALSL_D:       "左移加.长整",
	AALSL_W:       "左移加.普整",
	AALSL_WU:      "左移加.普正",
	AAMADD_B:      "AMADD.B",
	AAMADD_D:      "AMADD.D",
	AAMADD_DB_B:   "AMADD_DB.B",
	AAMADD_DB_D:   "AMADD_DB.D",
	AAMADD_DB_H:   "AMADD_DB.H",
	AAMADD_DB_W:   "AMADD_DB.W",
	AAMADD_H:      "AMADD.H",
	AAMADD_W:      "AMADD.W",
	AAMAND_D:      "AMAND.D",
	AAMAND_DB_D:   "AMAND_DB.D",
	AAMAND_DB_W:   "AMAND_DB.W",
	AAMAND_W:      "AMAND.W",
	AAMCAS_B:      "AMCAS.B",
	AAMCAS_D:      "AMCAS.D",
	AAMCAS_DB_B:   "AMCAS_DB.B",
	AAMCAS_DB_D:   "AMCAS_DB.D",
	AAMCAS_DB_H:   "AMCAS_DB.H",
	AAMCAS_DB_W:   "AMCAS_DB.W",
	AAMCAS_H:      "AMCAS.H",
	AAMCAS_W:      "AMCAS.W",
	AAMMAX_D:      "AMMAX.D",
	AAMMAX_DB_D:   "AMMAX_DB.D",
	AAMMAX_DB_DU:  "AMMAX_DB.DU",
	AAMMAX_DB_W:   "AMMAX_DB.W",
	AAMMAX_DB_WU:  "AMMAX_DB.WU",
	AAMMAX_DU:     "AMMAX.DU",
	AAMMAX_W:      "AMMAX.W",
	AAMMAX_WU:     "AMMAX.WU",
	AAMMIN_D:      "AMMIN.D",
	AAMMIN_DB_D:   "AMMIN_DB.D",
	AAMMIN_DB_DU:  "AMMIN_DB.DU",
	AAMMIN_DB_W:   "AMMIN_DB.W",
	AAMMIN_DB_WU:  "AMMIN_DB.WU",
	AAMMIN_DU:     "AMMIN.DU",
	AAMMIN_W:      "AMMIN.W",
	AAMMIN_WU:     "AMMIN.WU",
	AAMOR_D:       "AMOR.D",
	AAMOR_DB_D:    "AMOR_DB.D",
	AAMOR_DB_W:    "AMOR_DB.W",
	AAMOR_W:       "AMOR.W",
	AAMSWAP_B:     "AMSWAP.B",
	AAMSWAP_D:     "AMSWAP.D",
	AAMSWAP_DB_B:  "AMSWAP_DB.B",
	AAMSWAP_DB_D:  "AMSWAP_DB.D",
	AAMSWAP_DB_H:  "AMSWAP_DB.H",
	AAMSWAP_DB_W:  "AMSWAP_DB.W",
	AAMSWAP_H:     "AMSWAP.H",
	AAMSWAP_W:     "AMSWAP.W",
	AAMXOR_D:      "AMXOR.D",
	AAMXOR_DB_D:   "AMXOR_DB.D",
	AAMXOR_DB_W:   "AMXOR_DB.W",
	AAMXOR_W:      "AMXOR.W",
	AAND:          "AND",
	AANDI:         "ANDI",
	AANDN:         "ANDN",
	AASRTGT_D:     "ASRTGT.D",
	AASRTLE_D:     "ASRTLE.D",
	AB:            "B",
	ABCEQZ:        "BCEQZ",
	ABCNEZ:        "BCNEZ",
	ABEQ:          "BEQ",
	ABEQZ:         "BEQZ",
	ABGE:          "BGE",
	ABGEU:         "BGEU",
	ABITREV_4B:    "BITREV.4B",
	ABITREV_8B:    "BITREV.8B",
	ABITREV_D:     "BITREV.D",
	ABITREV_W:     "BITREV.W",
	ABL:           "BL",
	ABLT:          "BLT",
	ABLTU:         "BLTU",
	ABNE:          "BNE",
	ABNEZ:         "BNEZ",
	ABREAK:        "BREAK",
	ABSTRINS_D:    "BSTRINS.D",
	ABSTRINS_W:    "BSTRINS.W",
	ABSTRPICK_D:   "BSTRPICK.D",
	ABSTRPICK_W:   "BSTRPICK.W",
	ABYTEPICK_D:   "BYTEPICK.D",
	ABYTEPICK_W:   "BYTEPICK.W",
	ACACOP:        "CACOP",
	ACLO_D:        "CLO.D",
	ACLO_W:        "CLO.W",
	ACLZ_D:        "CLZ.D",
	ACLZ_W:        "CLZ.W",
	ACPUCFG:       "CPUCFG",
	ACRCC_W_B_W:   "CRCC.W.B.W",
	ACRCC_W_D_W:   "CRCC.W.D.W",
	ACRCC_W_H_W:   "CRCC.W.H.W",
	ACRCC_W_W_W:   "CRCC.W.W.W",
	ACRC_W_B_W:    "CRC.W.B.W",
	ACRC_W_D_W:    "CRC.W.D.W",
	ACRC_W_H_W:    "CRC.W.H.W",
	ACRC_W_W_W:    "CRC.W.W.W",
	ACSRRD:        "CSRRD",
	ACSRWR:        "CSRWR",
	ACSRXCHG:      "CSRXCHG",
	ACTO_D:        "CTO.D",
	ACTO_W:        "CTO.W",
	ACTZ_D:        "CTZ.D",
	ACTZ_W:        "CTZ.W",
	ADBAR:         "DBAR",
	ADBCL:         "DBCL",
	ADIV_D:        "某除某.长整",
	ADIV_DU:       "某除某.长正",
	ADIV_W:        "某除某.普整",
	ADIV_WU:       "某除某.普正",
	AERTN:         "ERTN",
	AEXT_W_B:      "EXT.W.B",
	AEXT_W_H:      "EXT.W.H",
	AFABS_D:       "FABS.D",
	AFABS_S:       "FABS.S",
	AFADD_D:       "FADD.D",
	AFADD_S:       "FADD.S",
	AFCLASS_D:     "FCLASS.D",
	AFCLASS_S:     "FCLASS.S",
	AFCMP_CAF_D:   "FCMP.CAF.D",
	AFCMP_CAF_S:   "FCMP.CAF.S",
	AFCMP_CEQ_D:   "FCMP.CEQ.D",
	AFCMP_CEQ_S:   "FCMP.CEQ.S",
	AFCMP_CLE_D:   "FCMP.CLE.D",
	AFCMP_CLE_S:   "FCMP.CLE.S",
	AFCMP_CLT_D:   "FCMP.CLT.D",
	AFCMP_CLT_S:   "FCMP.CLT.S",
	AFCMP_CNE_D:   "FCMP.CNE.D",
	AFCMP_CNE_S:   "FCMP.CNE.S",
	AFCMP_COR_D:   "FCMP.COR.D",
	AFCMP_COR_S:   "FCMP.COR.S",
	AFCMP_CUEQ_D:  "FCMP.CUEQ.D",
	AFCMP_CUEQ_S:  "FCMP.CUEQ.S",
	AFCMP_CULE_D:  "FCMP.CULE.D",
	AFCMP_CULE_S:  "FCMP.CULE.S",
	AFCMP_CULT_D:  "FCMP.CULT.D",
	AFCMP_CULT_S:  "FCMP.CULT.S",
	AFCMP_CUNE_D:  "FCMP.CUNE.D",
	AFCMP_CUNE_S:  "FCMP.CUNE.S",
	AFCMP_CUN_D:   "FCMP.CUN.D",
	AFCMP_CUN_S:   "FCMP.CUN.S",
	AFCMP_SAF_D:   "FCMP.SAF.D",
	AFCMP_SAF_S:   "FCMP.SAF.S",
	AFCMP_SEQ_D:   "FCMP.SEQ.D",
	AFCMP_SEQ_S:   "FCMP.SEQ.S",
	AFCMP_SLE_D:   "FCMP.SLE.D",
	AFCMP_SLE_S:   "FCMP.SLE.S",
	AFCMP_SLT_D:   "FCMP.SLT.D",
	AFCMP_SLT_S:   "FCMP.SLT.S",
	AFCMP_SNE_D:   "FCMP.SNE.D",
	AFCMP_SNE_S:   "FCMP.SNE.S",
	AFCMP_SOR_D:   "FCMP.SOR.D",
	AFCMP_SOR_S:   "FCMP.SOR.S",
	AFCMP_SUEQ_D:  "FCMP.SUEQ.D",
	AFCMP_SUEQ_S:  "FCMP.SUEQ.S",
	AFCMP_SULE_D:  "FCMP.SULE.D",
	AFCMP_SULE_S:  "FCMP.SULE.S",
	AFCMP_SULT_D:  "FCMP.SULT.D",
	AFCMP_SULT_S:  "FCMP.SULT.S",
	AFCMP_SUNE_D:  "FCMP.SUNE.D",
	AFCMP_SUNE_S:  "FCMP.SUNE.S",
	AFCMP_SUN_D:   "FCMP.SUN.D",
	AFCMP_SUN_S:   "FCMP.SUN.S",
	AFCOPYSIGN_D:  "FCOPYSIGN.D",
	AFCOPYSIGN_S:  "FCOPYSIGN.S",
	AFCVT_D_S:     "FCVT.D.S",
	AFCVT_S_D:     "FCVT.S.D",
	AFDIV_D:       "FDIV.D",
	AFDIV_S:       "FDIV.S",
	AFFINT_D_L:    "FFINT.D.L",
	AFFINT_D_W:    "FFINT.D.W",
	AFFINT_S_L:    "FFINT.S.L",
	AFFINT_S_W:    "FFINT.S.W",
	AFLDGT_D:      "FLDGT.D",
	AFLDGT_S:      "FLDGT.S",
	AFLDLE_D:      "FLDLE.D",
	AFLDLE_S:      "FLDLE.S",
	AFLDX_D:       "FLDX.D",
	AFLDX_S:       "FLDX.S",
	AFLD_D:        "FLD.D",
	AFLD_S:        "FLD.S",
	AFLOGB_D:      "FLOGB.D",
	AFLOGB_S:      "FLOGB.S",
	AFMADD_D:      "FMADD.D",
	AFMADD_S:      "FMADD.S",
	AFMAXA_D:      "FMAXA.D",
	AFMAXA_S:      "FMAXA.S",
	AFMAX_D:       "FMAX.D",
	AFMAX_S:       "FMAX.S",
	AFMINA_D:      "FMINA.D",
	AFMINA_S:      "FMINA.S",
	AFMIN_D:       "FMIN.D",
	AFMIN_S:       "FMIN.S",
	AFMOV_D:       "FMOV.D",
	AFMOV_S:       "FMOV.S",
	AFMSUB_D:      "FMSUB.D",
	AFMSUB_S:      "FMSUB.S",
	AFMUL_D:       "FMUL.D",
	AFMUL_S:       "FMUL.S",
	AFNEG_D:       "FNEG.D",
	AFNEG_S:       "FNEG.S",
	AFNMADD_D:     "FNMADD.D",
	AFNMADD_S:     "FNMADD.S",
	AFNMSUB_D:     "FNMSUB.D",
	AFNMSUB_S:     "FNMSUB.S",
	AFRECIPE_D:    "FRECIPE.D",
	AFRECIPE_S:    "FRECIPE.S",
	AFRECIP_D:     "FRECIP.D",
	AFRECIP_S:     "FRECIP.S",
	AFRINT_D:      "FRINT.D",
	AFRINT_S:      "FRINT.S",
	AFRSQRTE_D:    "FRSQRTE.D",
	AFRSQRTE_S:    "FRSQRTE.S",
	AFRSQRT_D:     "FRSQRT.D",
	AFRSQRT_S:     "FRSQRT.S",
	AFSCALEB_D:    "FSCALEB.D",
	AFSCALEB_S:    "FSCALEB.S",
	AFSEL:         "FSEL",
	AFSQRT_D:      "FSQRT.D",
	AFSQRT_S:      "FSQRT.S",
	AFSTGT_D:      "FSTGT.D",
	AFSTGT_S:      "FSTGT.S",
	AFSTLE_D:      "FSTLE.D",
	AFSTLE_S:      "FSTLE.S",
	AFSTX_D:       "FSTX.D",
	AFSTX_S:       "FSTX.S",
	AFST_D:        "FST.D",
	AFST_S:        "FST.S",
	AFSUB_D:       "FSUB.D",
	AFSUB_S:       "FSUB.S",
	AFTINTRM_L_D:  "FTINTRM.L.D",
	AFTINTRM_L_S:  "FTINTRM.L.S",
	AFTINTRM_W_D:  "FTINTRM.W.D",
	AFTINTRM_W_S:  "FTINTRM.W.S",
	AFTINTRNE_L_D: "FTINTRNE.L.D",
	AFTINTRNE_L_S: "FTINTRNE.L.S",
	AFTINTRNE_W_D: "FTINTRNE.W.D",
	AFTINTRNE_W_S: "FTINTRNE.W.S",
	AFTINTRP_L_D:  "FTINTRP.L.D",
	AFTINTRP_L_S:  "FTINTRP.L.S",
	AFTINTRP_W_D:  "FTINTRP.W.D",
	AFTINTRP_W_S:  "FTINTRP.W.S",
	AFTINTRZ_L_D:  "FTINTRZ.L.D",
	AFTINTRZ_L_S:  "FTINTRZ.L.S",
	AFTINTRZ_W_D:  "FTINTRZ.W.D",
	AFTINTRZ_W_S:  "FTINTRZ.W.S",
	AFTINT_L_D:    "FTINT.L.D",
	AFTINT_L_S:    "FTINT.L.S",
	AFTINT_W_D:    "FTINT.W.D",
	AFTINT_W_S:    "FTINT.W.S",
	AIBAR:         "IBAR",
	AIDLE:         "IDLE",
	AINVTLB:       "INVTLB",
	AIOCSRRD_B:    "IOCSRRD.B",
	AIOCSRRD_D:    "IOCSRRD.D",
	AIOCSRRD_H:    "IOCSRRD.H",
	AIOCSRRD_W:    "IOCSRRD.W",
	AIOCSRWR_B:    "IOCSRWR.B",
	AIOCSRWR_D:    "IOCSRWR.D",
	AIOCSRWR_H:    "IOCSRWR.H",
	AIOCSRWR_W:    "IOCSRWR.W",
	AJIRL:         "JIRL",
	ALDDIR:        "LDDIR",
	ALDGT_B:       "LDGT.B",
	ALDGT_D:       "LDGT.D",
	ALDGT_H:       "LDGT.H",
	ALDGT_W:       "LDGT.W",
	ALDLE_B:       "LDLE.B",
	ALDLE_D:       "LDLE.D",
	ALDLE_H:       "LDLE.H",
	ALDLE_W:       "LDLE.W",
	ALDPTE:        "LDPTE",
	ALDPTR_D:      "LDPTR.D",
	ALDPTR_W:      "LDPTR.W",
	ALDX_B:        "LDX.B",
	ALDX_BU:       "LDX.BU",
	ALDX_D:        "LDX.D",
	ALDX_H:        "LDX.H",
	ALDX_HU:       "LDX.HU",
	ALDX_W:        "LDX.W",
	ALDX_WU:       "LDX.WU",
	ALD_B:         "LD.B",
	ALD_BU:        "LD.BU",
	ALD_D:         "LD.D",
	ALD_H:         "LD.H",
	ALD_HU:        "LD.HU",
	ALD_W:         "LD.W",
	ALD_WU:        "LD.WU",
	ALLACQ_D:      "LLACQ.D",
	ALLACQ_W:      "LLACQ.W",
	ALL_D:         "LL.D",
	ALL_W:         "LL.W",
	ALU12I_W:      "常赋某.普整.十二常",
	ALU32I_D:      "常赋某.长整.三二常",
	ALU52I_D:      "常赋某.长整.五二常",
	AMASKEQZ:      "MASKEQZ",
	AMASKNEZ:      "MASKNEZ",
	AMOD_D:        "某模某.长整",
	AMOD_DU:       "某模某.长正",
	AMOD_W:        "某模某.普整",
	AMOD_WU:       "某模某.普正",
	AMOVCF2FR:     "MOVCF2FR",
	AMOVCF2GR:     "MOVCF2GR",
	AMOVFCSR2GR:   "MOVFCSR2GR",
	AMOVFR2CF:     "MOVFR2CF",
	AMOVFR2GR_D:   "MOVFR2GR.D",
	AMOVFR2GR_S:   "MOVFR2GR.S",
	AMOVFRH2GR_S:  "MOVFRH2GR.S",
	AMOVGR2CF:     "MOVGR2CF",
	AMOVGR2FCSR:   "MOVGR2FCSR",
	AMOVGR2FRH_W:  "MOVGR2FRH.W",
	AMOVGR2FR_D:   "MOVGR2FR.D",
	AMOVGR2FR_W:   "MOVGR2FR.W",
	AMULH_D:       "某乘某.长整.高位",
	AMULH_DU:      "某乘某.长正.高位",
	AMULH_W:       "某乘某.普整.高位",
	AMULH_WU:      "某乘某.普正.高位",
	AMULW_D_W:     "某乘某.长整.普整",
	AMULW_D_WU:    "某乘某.长整.普正",
	AMUL_D:        "某乘某.长整",
	AMUL_W:        "某乘某.普整",
	ANOR:          "NOR",
	AOR:           "OR",
	AORI:          "ORI",
	AORN:          "ORN",
	APCADDI:       "PCADDI",
	APCADDU12I:    "PCADDU12I",
	APCADDU18I:    "PCADDU18I",
	APCALAU12I:    "PCALAU12I",
	APRELD:        "PRELD",
	APRELDX:       "PRELDX",
	ARDTIMEH_W:    "RDTIMEH.W",
	ARDTIMEL_W:    "RDTIMEL.W",
	ARDTIME_D:     "RDTIME.D",
	AREVB_2H:      "REVB.2H",
	AREVB_2W:      "REVB.2W",
	AREVB_4H:      "REVB.4H",
	AREVB_D:       "REVB.D",
	AREVH_2W:      "REVH.2W",
	AREVH_D:       "REVH.D",
	AROTRI_D:      "ROTRI.D",
	AROTRI_W:      "ROTRI.W",
	AROTR_D:       "ROTR.D",
	AROTR_W:       "ROTR.W",
	ASCREL_D:      "SCREL.D",
	ASCREL_W:      "SCREL.W",
	ASC_D:         "SC.D",
	ASC_Q:         "SC.Q",
	ASC_W:         "SC.W",
	ASLLI_D:       "SLLI.D",
	ASLLI_W:       "SLLI.W",
	ASLL_D:        "SLL.D",
	ASLL_W:        "SLL.W",
	ASLT:          "SLT",
	ASLTI:         "SLTI",
	ASLTU:         "SLTU",
	ASLTUI:        "SLTUI",
	ASRAI_D:       "SRAI.D",
	ASRAI_W:       "SRAI.W",
	ASRA_D:        "SRA.D",
	ASRA_W:        "SRA.W",
	ASRLI_D:       "SRLI.D",
	ASRLI_W:       "SRLI.W",
	ASRL_D:        "SRL.D",
	ASRL_W:        "SRL.W",
	ASTGT_B:       "STGT.B",
	ASTGT_D:       "STGT.D",
	ASTGT_H:       "STGT.H",
	ASTGT_W:       "STGT.W",
	ASTLE_B:       "STLE.B",
	ASTLE_D:       "STLE.D",
	ASTLE_H:       "STLE.H",
	ASTLE_W:       "STLE.W",
	ASTPTR_D:      "STPTR.D",
	ASTPTR_W:      "STPTR.W",
	ASTX_B:        "STX.B",
	ASTX_D:        "STX.D",
	ASTX_H:        "STX.H",
	ASTX_W:        "STX.W",
	AST_B:         "ST.B",
	AST_D:         "ST.D",
	AST_H:         "ST.H",
	AST_W:         "ST.W",
	ASUB_D:        "某减某.长整",
	ASUB_W:        "某减某.普整",
	ASYSCALL:      "SYSCALL",
	ATLBCLR:       "TLBCLR",
	ATLBFILL:      "TLBFILL",
	ATLBFLUSH:     "TLBFLUSH",
	ATLBRD:        "TLBRD",
	ATLBSRCH:      "TLBSRCH",
	ATLBWR:        "TLBWR",
	AXOR:          "XOR",
	AXORI:         "XORI",
}
