// Auto Generated by https://wa-lang.org/wa/wat2c. DONOT EDIT!!!

// module wa-arduino-hello

#pragma once

#ifndef _app_H_
#define _app_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern void app_init();

// func $loop
extern void app_loop();

#ifdef __cplusplus
} // extern C 
#endif

#endif // _app_H_
