# Copyright (C) 2025 武汉凹语言科技有限公司
# SPDX-License-Identifier: AGPL-3.0-or-later

run:
	go run ../../../main.go fib.wa

test:
	go run ../../../main.go test test_fib.wa

test-run:
	go run ../../../main.go test -run=Example test_fib.wa

clean:
